#!/bin/sh

set -e

VIM_D=${VIM_D:-$HOME/.vim}
echo $VIM_D

test -d $VIM_D || git clone https://github.com/skotchpine/dots $VIM_D

for dir in autoload bundle; do
  test -d $VIM_D/$dir || mkdir -p $VIM_D/$dir
done

pathogen_src=https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
pathogen_dest=$VIM_D/autoload/pathogen.vim
test -f $pathogen_dest || curl $pathogen_src > $pathogen_dest

origin=$(pwd)
cd $VIM_D/bundle; {
  for repo in $(cat $VIM_D/manifest); do
    echo "test -d $(basename $repo | sed -e 's/\.git//') || git clone $repo"
    test -d $(basename $repo | sed -e 's/\.git//') || git clone $repo
  done
}; cd $origin
